version: '2.3'

services:
  postgres:
    image: postgres:9.6-alpine
    ports:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Kyt12!
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      target: development
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=test
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=Kyt12!
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres

  test:
    build:
      context: .
      target: development
    command: npm test
    environment:
      - PORT=3000
      - NODE_ENV=test
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=Kyt12!
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres


